### ISSUE TITLE
TypeError: cannot insert DatetimeArray with incompatible label

### ISSUE THREAD

**Issue by rahulmr** [dmitriiweb/tapy#2]
Getting error => TypeError: cannot insert DatetimeArray with incompatible label for alligator

```python
from tapy import Indicators
import yfinance as yf

def test_tapy():
    sbin = yf.Ticker("SBIN.NS")
    df = sbin.history(period="7d", interval="15m")
    df.drop('Dividends', axis=1, inplace=True)
    df.drop('Stock Splits', axis=1, inplace=True)
    print(df)
    ohlcv = df.copy()
    # ohlcv['Date'] = ohlcv['Date']
    # ohlcv['Open'] = df['open']
    # ohlcv['High'] = df['high']
    # ohlcv['Low'] = df['low']
    # ohlcv['Close'] = df['close']
    # ohlcv['Volume'] = df['volume']
    indicators = Indicators(ohlcv)
    # indicators.accelerator_oscillator(column_name='AC')
    # indicators.sma()
    # indicators.fractals(column_name_high='fractals_high',
    #                     column_name_low='fractals_low')
    indicators.alligator(period_jaws=13, period_teeth=8, period_lips=5, shift_jaws=8, shift_teeth=5, shift_lips=3,
                         column_name_jaws='alligator_jaw', column_name_teeth='alligator_teeth', column_name_lips='alligator_lips')
    ohlcv = indicators.df
    print(ohlcv.tail())


if __name__ == '__main__':
    test_tapy()


```
Output
```
(venv) PS D:\trading\kiteconnect_bypass> python .\pandas_ta_test.py
                                 Open        High         Low       Close   Volume
Datetime
2021-01-13 09:15:00+05:30  295.600006  299.100006  295.600006  298.600006  3936352
2021-01-13 09:30:00+05:30  298.600006  302.000000  298.600006  299.950012  7484116
2021-01-13 09:45:00+05:30  299.850006  300.500000  299.399994  300.149994  2147081
2021-01-13 10:00:00+05:30  300.149994  301.950012  300.049988  300.500000  3226762
2021-01-13 10:15:00+05:30  300.450012  300.750000  299.250000  300.000000  2123864
...                               ...         ...         ...         ...      ...
2021-01-21 14:15:00+05:30  298.299988  300.000000  298.250000  299.450012  1014981
2021-01-21 14:30:00+05:30  299.500000  299.500000  298.500000  298.649994  1221188
2021-01-21 14:45:00+05:30  298.700012  298.799988  295.399994  297.850006  2193808
2021-01-21 15:00:00+05:30  297.950012  297.950012  291.549988  294.799988  4009263
2021-01-21 15:15:00+05:30  294.850006  297.000000  294.500000  296.899994  2718277

[175 rows x 5 columns]
Traceback (most recent call last):
  File "D:\trading\kiteconnect_bypass\venv\lib\site-packages\pandas\core\indexes\base.py", line 2898, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 1675, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 1683, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'alligator_jaw'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\trading\kiteconnect_bypass\venv\lib\site-packages\pandas\core\frame.py", line 3146, in _set_value
    series = self._get_item_cache(col)
  File "D:\trading\kiteconnect_bypass\venv\lib\site-packages\pandas\core\generic.py", line 3542, in _get_item_cache
    loc = self.columns.get_loc(item)
  File "D:\trading\kiteconnect_bypass\venv\lib\site-packages\pandas\core\indexes\base.py", line 2900, in get_loc
    raise KeyError(key) from err
KeyError: 'alligator_jaw'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\trading\kiteconnect_bypass\pandas_ta_test.py", line 71, in <module>
    test_tapy()
  File "D:\trading\kiteconnect_bypass\pandas_ta_test.py", line 64, in test_tapy
    indicators.alligator(period_jaws=13, period_teeth=8, period_lips=5, shift_jaws=8, shift_teeth=5, shift_lips=3,
  File "D:\trading\kiteconnect_bypass\venv\lib\site-packages\tapy\indicators.py", line 229, in alligator
    df_j = calculate_smma(df_median, period_jaws, column_name_jaws, median_col)
  File "D:\trading\kiteconnect_bypass\venv\lib\site-packages\tapy\utils.py", line 33, in calculate_smma
    df_tmp.at[period, column_name] = first_val
  File "D:\trading\kiteconnect_bypass\venv\lib\site-packages\pandas\core\indexing.py", line 2089, in __setitem__
    return super().__setitem__(key, value)
  File "D:\trading\kiteconnect_bypass\venv\lib\site-packages\pandas\core\indexing.py", line 2040, in __setitem__
    self.obj._set_value(*key, value=value, takeable=self._takeable)
  File "D:\trading\kiteconnect_bypass\venv\lib\site-packages\pandas\core\frame.py", line 3159, in _set_value
    self.loc[index, col] = value
  File "D:\trading\kiteconnect_bypass\venv\lib\site-packages\pandas\core\indexing.py", line 670, in __setitem__
    iloc._setitem_with_indexer(indexer, value)
  File "D:\trading\kiteconnect_bypass\venv\lib\site-packages\pandas\core\indexing.py", line 1610, in _setitem_with_indexer
    labels = index.insert(len(index), key)
  File "D:\trading\kiteconnect_bypass\venv\lib\site-packages\pandas\core\indexes\datetimelike.py", line 955, in insert
    item = self._data._validate_insert_value(item)
  File "D:\trading\kiteconnect_bypass\venv\lib\site-packages\pandas\core\arrays\datetimelike.py", line 884, in _validate_insert_value
    value = self._validate_scalar(value, msg, cast_str=False)
  File "D:\trading\kiteconnect_bypass\venv\lib\site-packages\pandas\core\arrays\datetimelike.py", line 817, in _validate_scalar
    raise TypeError(msg)
TypeError: cannot insert DatetimeArray with incompatible label

```

**Comment by dmitriiweb** [comment]
`ohlcv.reset_index(level=0, inplace=True)`
